In [ ]:
import numpy as np

In [ ]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arryBoolean=np.arange(9).reshape(3,3)>=0
arryBoolean

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
arrRand=np.random.randint(5,50,10)
arrRand

array([14, 23, 35, 40, 49, 36, 43, 25, 17, 11])

In [ ]:
matr=np.arange(16).reshape(4,4)
matr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
arrEven=np.arange(2,22,2)
arrEven

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr=[12, 45, 67, 23, 89, 34]
np.max(arr)

np.int64(89)

In [ ]:
np.min(arr)

np.int64(12)

In [ ]:
np.mean(arr)

np.float64(45.0)

In [ ]:
reverse=np.array(arr[::-1])
reverse

array([34, 89, 23, 67, 45, 12])

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1
odd_numbers = arr[arr % 2 != 0]
odd_numbers

array([-1, -1, -1, -1, -1])

In [ ]:
Mat1=np.arange(9).reshape(3,3)
Mat1


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
Mat2=np.arange(10,19).reshape(3,3)
Mat2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
Mat1+Mat2

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26]])

In [ ]:
Mat2-Mat1

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [ ]:
Mat5=np.arange(25).reshape(5,5)
Mat5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
np.mean(Mat5,axis=1)

array([ 2.,  7., 12., 17., 22.])

In [ ]:
np.mean(Mat5,axis=0)

array([10., 11., 12., 13., 14.])

In [ ]:
arr=np.random.rand(4,4)
mean=np.mean(arr)
standDev=np.std(arr)

In [ ]:
standDev

np.float64(0.31710526253386334)

In [ ]:
mean

np.float64(0.5075561154074446)

In [ ]:
(arr-mean)/standDev

array([[ 1.11070895, -0.60956815, -0.56853127,  0.88633913],
       [-1.55161906, -0.5966659 ,  0.50491062,  1.39887792],
       [-0.10265673, -0.89605514, -1.55518782, -1.19560419],
       [ 1.01480906,  0.01714398,  0.66998832,  1.47311028]])

In [ ]:
arr=np.arange(0,100,5)
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [ ]:
newArr=arr[arr>50]
newArr

array([55, 60, 65, 70, 75, 80, 85, 90, 95])

In [ ]:
arr=np.arange(1,100)*10
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260,
       270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390,
       400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520,
       530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640, 650,
       660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770, 780,
       790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890, 900, 910,
       920, 930, 940, 950, 960, 970, 980, 990])

In [ ]:
arr[(arr>30)|(arr<70)]=np.mean(arr)
arr

array([500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500])